# Generated by Django 5.0.1 on 2024-01-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Faculty',
            field=models.CharField(choices=[('Computing', 'Computing'), ('Medcine', 'Medcine'), ('Health science', 'Health science'), ('Engineering', 'Engineering'), ('Account', 'Account')], max_length=100),
        ),
    ]
